Create database SGA;

create table disciplina (
cod serial primary key,
nome varchar(100) not null,
curso varchar(100),
carga_horaria numeric(3,0)
);
create table turma (
cod serial primary key,
Periodo varchar(100) not null,
nome varchar(100) not null,
tipo varchar(100) not null,
quant_alunos numeric(3,0)
);

create table docente (
cod serial primary key,
nome varchar(100) not null,
cargo varchar(100) not null
);
create table atribuicao (
cod serial primary key,
cod_disciplina integer,
cod_turma integer,
cod_docente integer,
FOREIGN KEY(cod_disciplina) REFERENCES disciplina(cod),
FOREIGN KEY(cod_turma) REFERENCES turma(cod),
FOREIGN KEY(cod_docente) REFERENCES docente(cod)
);
create table aula (
cod serial primary key,
cod_atribuicao integer,
descricao varchar(100) not null,
FOREIGN KEY(cod_atribuicao) REFERENCES atribuicao(cod)
);
create table horario (
cod serial primary key,
cod_aula integer,
horario_inicio timestamp,
horario_fim timestamp,
FOREIGN KEY(cod_aula) REFERENCES aula(cod)
);
create table ambiente (
cod serial primary key,
cod_horario integer,
nome varchar(100) not null,
tipo varchar(100) not null,
local varchar(100) not null,
FOREIGN KEY(cod_horario) REFERENCES horario(cod)
);

insert into disciplina (nome) values
('Ad'),
('Aeac'),
('Aem'),
('Ajm'),
('An'),
('Ari'),
('Armz'),
('As'),
('Atiex'),
('Au'),
('Auc'),
('Auph'),
('Bcd'),
('Caapl'),
('Cad'),
('Calc'),
('Cam'),
('Capus'),
('Cer'),
('Ciema'),
('Cl'),
('Clpr'),
('Cmu'),
('Co'),
('Coe'),
('Cones'),
('Conuv'),
('Cort'),
('Cost'),
('Crd'),
('Ctecn'),
('Ddp'),
('Depp'),
('Det3D'),
('Dewfe'),
('Dist'),
('Dm'),
('Dme'),
('Dpco'),
('Eac'),
('Easa'),
('Eleac'),
('Ensof'),
('Eprod'),
('Ex'),
('Exa'),
('Exb'),
('Farh'),
('Fcf'),
('Fdel'),
('Fdmt'),
('Fea'),
('Ferdi'),
('Fgor'),
('Finel'),
('Fmipa'),
('Fol'),
('Fpfm'),
('Fpl'),
('Fpmi'),
('Fqp'),
('Fu'),
('Fuao'),
('Funci'),
('Fundp'),
('Funpl'),
('Fus'),
('Fusi'),
('Gem'),
('Geor'),
('Gepco'),
('Gepe'),
('Gepr'),
('Gmasm'),
('Gr'),
('Hi'),
('Hip'),
('Icibe'),
('Idq'),
('Iepr'),
('Ifaci'),
('Il'),
('Imcve'),
('In'),
('Iniot'),
('Isau'),
('Iscf'),
('Isei'),
('Iseli'),
('Isng'),
('Itcoi'),
('Iveho'),
('Le'),
('Lec'),
('Ledi'),
('Ler'),
('Li'),
('Lidt'),
('Lidtm'),
('Lima'),
('Lip'),
('Lm'),
('Lop'),
('Lopal'),
('Maau'),
('Mags'),
('Map'),
('Maq'),
('Masa'),
('Matu'),
('Mcei'),
('Mcmp'),
('Me'),
('Mé'),
('Meei'),
('Metc'),
('Metca'),
('Mi'),
('Mmet'),
('Moi'),
('Moiel'),
('Mrg'),
('Msexc'),
('Mspow'),
('Mswor'),
('Mtr'),
('Oceus'),
('Oea'),
('Opelo'),
('Otcnc'),
('Pbe'),
('Pcin'),
('Pend'),
('Pfm'),
('Pint1'),
('Pint3'),
('Pint5'),
('Pleti'),
('Plo'),
('Pmec'),
('Ppdm'),
('Ppe'),
('Ppocu'),
('Pputf'),
('Pr'),
('Prarh'),
('Pre'),
('Prens'),
('Prmec'),
('Psaee'),
('Psmi'),
('Pso'),
('Psof'),
('Ptcn'),
('Ptorc'),
('Raum'),
('Rbind'),
('Reem'),
('Resce'),
('Rlad'),
('Roafc'),
('Roalo'),
('Roarh'),
('Rse'),
('Rspce'),
('Seex'),
('Seit'),
('Selan'),
('Seldi'),
('Semb'),
('Sepeh'),
('Sigla'),
('Sistq'),
('Sitm'),
('So'),
('Sop'),
('Spi'),
('Sse'),
('Sstr'),
('Tcrx'),
('Tdi'),
('Temcp'),
('Tinco'),
('Tmn'),
('Tpmc'),
('Tran'),
('Trdsi'),
('Tsof'),
('Umc'),
('Unc'),
('Vidce'),
('Vidse'),
('Wh'),
('Ye');

insert into turma (periodo, nome, tipo) values
('Manhã','M1-AA-SCHA','Aprendizagem'),
('Manhã','M1AA','Aprendizagem'),
('Tarde','T1-AA-SABESP','Aprendizagem'),
('Tarde','T1AA-CORREIOS','Aprendizagem'),
('Inexistente','T1AL-CORREIOS','Aprendizagem'),
('Manhã','M1-ALP','Aprendizagem'),
('Integral','I1CECDR','Aprendizagem'),
('Manhã','M2COST-EMPHASIS','Aprendizagem'),
('Tarde','T2COST-EMPHASIS','Aprendizagem'),
('Manhã','M1EME','Aprendizagem'),
('Manhã','M2EME','Aprendizagem'),
('Tarde','T1EME','Aprendizagem'),
('Tarde','T3EME','Aprendizagem'),
('Tarde','T2-MBMC-SUZ','Aprendizagem'),
('Integral','I1MUECDR A','Aprendizagem'),
('Integral','I1MUECDR B','Aprendizagem'),
('Integral','I1MUECDR C','Aprendizagem'),
('Tarde','T1-OMPMI-SCHA','Aprendizagem'),
('Tarde','T1-OMPMI-ZF','Aprendizagem'),
('Manhã','M2-OPFM-SCHA','Aprendizagem'),
('Tarde','T1-OPFM-SCHA','Aprendizagem'),
('Tarde','T2-OPFM-SCHA','Aprendizagem'),
('Integral','I1PECDR','Aprendizagem'),
('Manhã','M1-MEC-TOY','Nível Técnico'),
('Manhã','M2-MEC-BOSCH','Nível Técnico'),
('Tarde','T2-MEC-TOY','Nível Técnico'),
('Integral','CT-DEV-ITAPE-1E','Nível Técnico'),
('Integral','CT-DEV-ITAPE-1F','Nível Técnico'),
('Integral','CT-DEV-ITAPE-2E','Nível Técnico'),
('Integral','CT-DEV-ITAPE-2F','Nível Técnico'),
('Integral','CT-DEV-SENAI-1A','Nível Técnico'),
('Integral','CT-DEV-SENAI-1B','Nível Técnico'),
('Integral','CT-DEV-SENAI-2A','Nível Técnico'),
('Integral','CT-DEV-SENAI-2B','Nível Técnico'),
('Integral','CT-MEC-1A/B','Nível Técnico'),
('Integral','CT-MEC-1C/D','Nível Técnico'),
('Integral','CT-MEC-1E/F','Nível Técnico'),
('Integral','CT-MEC-2A/B','Nível Técnico'),
('Integral','CT-MEC-2C/D','Nível Técnico'),
('Integral','CT-MEC-2E/F','Nível Técnico');

insert into docente (nome, cargo) values
('Alexandre Rodrigues Matias Rigoni','Coordenador de Ativ Tecnica e Pedagogica'),
('Andre Cassulino Araujo Souza','Prof Educ Sup - Assistente II'),
('Roseli Nascimento Pimentel','Coordenador Administrativo e Financeiro'),
('Jose Dos Santos Brito','Orientador de Pratica Profissional'),
('Osmar Aleixo de Lima Cruz','Instrutor de Formacao Profissional III'),
('Irene da Natividade Lucia Neto','Assistente de Servicos Administrativos'),
('Fabio Rocha da Silveira','Diretor de Unid de Formacao Profissional'),
('Ronaldo Francisco do Amaral Soares','Assistente de Servicos Administrativos'),
('Jucilene Fernanda de Almeida','Coordenador de Relacion Com A Industria'),
('Wellington Benedito','Instrutor de Formacao Profissional II'),
('Amilton Joaquim Cordeiro de Freitas','Prof Educ Sup - Assistente II'),
('Ederson Duarte Bonfim','Prof Educ Sup - Especialista I'),
('Guilherme Lima Leite','Instrutor de Formacao Profissional II'),
('Ariane Diniz Silva','Prof Edu Sup - Adjunto II'),
('Hudson Luiz Pissini','Prof Educ Sup - Especialista I'),
('Rogerio Aparecido Silva','Coordenador de Ativ Tecnica e Pedagogica'),
('Edilson Alves Dos Santos','Instrutor de Formacao Profissional III'),
('Luciana Sayuri Fugita','Instrutor de Formacao Profissional III'),
('Caina Antunes Silva','Prof Educ Sup - Especialista II'),
('Lucas Miguel Leal da Silva','Coordenador de Ativ Tecnica e Pedagogica'),
('Alberto Carlos Belchior','Oficial de Manutencao I'),
('Ismael Manso de Oliveira','Oficial de Manutencao II'),
('Antonio Luiz de Oliveira','Oficial de Manutencao I'),
('Ana Paula Oliveira Schmitt','Analista de Qualidade de Vida'),
('Jose Rafael Claro da Silva','Instrutor de Formacao Profissional III'),
('Wilian Luz Ribeiro','Instrutor de Formacao Profissional III'),
('Anderson Henrique Lourenzetti Peres','Instrutor de Formacao Profissional II'),
('Alessandro Caetano','Instrutor de Formacao Profissional III'),
('Ronaldo Aparecido da Silva','Instrutor de Formacao Profissional II'),
('Fabio Augusto Marius','Professor Cai'),
('Beatriz Rosa de Brito Novaque','Assistente de Apoio Tecnico'),
('Sandra Regina Barbosa de Souza','Instrutor de Formacao Profissional II'),
('Simone de Souza Antunes','Instrutor de Formacao Profissional II'),
('Orlando Fernandes de Oliveira','Oficial de Manutencao I'),
('Rubens Theodoro','Supervisor de Serv de Manut Conservacao'),
('Janete Aparecida Luz Ribeiro','Instrutor de Formacao Profissional I'),
('Gabriel Claro da Silva','Prof Educ Sup - Especialista II'),
('Andre Brustoloni Rusconi','Prof Educ Sup - Especialista II'),
('Alexandre Dos Santos Almeida','Consultor Em Tecnologia II'),
('Daniel da Cruz','Consultor Em Tecnologia II'),
('Mauricio Aparecido Nunes','Instrutor de Formacao Profissional II'),
('Vivian Rodrigues Arrojo','Professor Cai'),
('Andre Caetano da Silva','Instrutor de Formacao Profissional III'),
('Samuel Martins Alavarse','Instrutor de Formacao Profissional III'),
('Joao Rodrigues Neto','Lider Tecnico'),
('Daniel Fernandez de Siqueira','Oficial de Manutencao I'),
('Reginaldo Siqueira Pinheiro','Ifp II - Horista'),
('Luis Claudio de Angelo','Consultor Em Tecnologia II'),
('Fabricio de Araujo Pelegrini','Instrutor de Formacao Profissional II'),
('Alex Paulo Ezequiel','Analista de Tecnologia'),
('Jessica Cristina Cardoso Prestes','Assistente de Servicos Administrativos'),
('Vinicius Prado Dos Santos','Instrutor de Formacao Profissional III'),
('Luciana de Fatima Moreira','Bibliotecario'),
('Renato Pinheiro Munhoz Tomal','Instrutor de Formacao Profissional III'),
('Emerson da Silva Santos','Instrutor de Formacao Profissional I'),
('Suzelia Maria da Costa','Instrutor de Formacao Profissional I'),
('Alessandro Cardoso','Consultor Em Tecnologia I'),
('Leandro Gaudio Rosa','Instrutor de Formacao Profissional III'),
('Emerson Martins de Magalhaes','Instrutor de Formacao Profissional III'),
('Pablo Marcello da Costa','Ifp III - Horista'),
('Marina Helena Pereira Vieira','Consultor Em Tecnologia I'),
('Roosevelt Barbosa Dos Santos','Ifp II - Horista'),
('Fernando Cesar da Costa Ayres','Assistente de Servicos Tecnicos'),
('Aline Cristine de Souza','Instrutor de Formacao Profissional II'),
('Andre Luiz Goncalves Rodrigues','Instrutor de Formacao Profissional II'),
('Jeferson Jorge Carvalho Rodrigues','Consultor Em Tecnologia I'),
('Sofia Pollefrone','Assistente de Servicos Administrativos'),
('Adilson Pereira da Silva','Instrutor de Formacao Profissional III'),
('Matheus Vinicius Almeida Moura','Consultor Em Tecnologia II'),
('Paulo Henrique Amaral','Consultor Em Tecnologia I'),
('Gabriela Eduarda Fraga','Consultor Em Tecnologia I'),
('Thiago Gregorio Dos Santos','Instrutor de Formacao Profissional III'),
('Saulo Henrique Garcia Marcuz','Consultor Em Tecnologia II'),
('Wellington Correia Borsato Junior','Instrutor de Formacao Profissional III'),
('Evandro Juvenal Jacinto','Instrutor de Formacao Profissional II'),
('Luis Felipe Banhos Peres','Instrutor de Formacao Profissional III'),
('Jose Henrique Quinteiro de Oliveira Junior','Instrutor de Formacao Profissional II'),
('Clayton Xavier de Macedo','Consultor Em Tecnologia I'),
('Lucibele Aparecida de Oliveira Silva','Ifp I - Horista'),
('Jose Antonio Leite','Instrutor de Formacao Profissional I'),
('Matheus Fernandes Medeiros','Instrutor de Formacao Profissional II'),
('Tatiane Ianaconi Seabra','Ifp II - Horista'),
('Jeniffer Steffani Vitor','Auxiliar de Expediente'),
('Grayce Kelly Delgado','Instrutor de Formacao Profissional II'),
('Antonio Fernando Dos Santos','Ifp II - Horista'),
('Suelen Paula Oliveira','Consultor Em Tecnologia I'),
('Bruno Cesar Leite','Instrutor de Formacao Profissional III'),
('Fabio Bitencourt Ribeiro','Instrutor de Formacao Profissional III'),
('Jurandir de Campos','Instrutor de Formacao Profissional III'),
('Adriano Rosa Mazetto','Instrutor de Formacao Profissional III'),
('Diego Rossi','Prof Educ Sup - Especialista II'),
('Vedilson do Prado Dos Santos','Instrutor de Formacao Profissional III'),
('Erica Aparecida Martins Siqueira','Instrutor de Formacao Profissional III'),
('Andre Luis de Mello Almeida Junior','Instrutor de Formacao Profissional III'),
('Daniel Teixeira Cintori','Instrutor de Formacao Profissional III'),
('Maria Salete Victor de Almeida','Bibliotecario'),
('Fernando Aparecido Camargo','Ifp II - Horista'),
('Glauco Todesco','Prof Educ Sup - Assistente II'),
('Tatiana Veiga Uzeloto','Assistente de Servicos Administrativos'),
('Newton Otavio Rodrigues de Melo Souza','Consultor Em Tecnologia I');

insert into ambiente (nome, tipo, local) values
('LAB. INFO 1','SALA','SETOR A TERREO'),
('LAB. INFO 2','SALA','SETOR A TERREO'),
('METROLOGIA/ENSAIOS','SALA','SETOR A TERREO'),
('ELETRONICA/AUTOMAÇÃO','SALA','SETOR A TERREO'),
('LABORATÓRIO DE CLP 1','SALA','SETOR A TERREO'),
('LABORATÓRIO DE CLP 2','SALA','SETOR A TERREO'),
('CAD/CAM 1','SALA','SETOR A TÉRREO'),
('CAD/CAM 2','SALA','SETOR A TERREO'),
('COORDENAÇÃO TÉCNICA/PEDAGO','SALA','SETOR A TERREO'),
('OFICINA ELETRONICA','OFICINA','SETOR A TERREO'),
('OFICINA ELETRICA','OFICINA','SETOR A TERREO'),
('OFICINA CNC FERRAMENTARIA','OFICINA','SETOR A TERREO'),
('OFICINA TORNEARIA FERRAMENTARIA','OFICINA','SETOR A TERREO'),
('OFICINA AJUSTAGEM FERRAMENTARIA','OFICINA','SETOR A TERREO'),
('OFICINA ESTAMPARIA FERRAMENTARIA','OFICINA','SETOR A TERREO'),
('OFICINA AJUSTAGEM 2','OFICINA','SETOR A TERREO'),
('OFICINA TORNEARIA 2','OFICINA','SETOR A TERREO'),
('OFICINA CNC 2','OFICINA','SETOR A TERREO'),
('DEPÓSITO CORREDOR ELÉTRICA','SALA','SETOR B TERREO'),
('PLANTA INDUSTRIA 4.0','SALA','SETOR B TERREO'),
('LAB. HIDRAULICA','SALA','SETOR B TERREO'),
('LAB. PENEUMÁTICA','SALA','SETOR B TERREO'),
('SALA 7-AUDITÓRIO','SALA','SETOR B TERREO'),
('SALA 6-AUDITÓRIO - DESENHO','SALA','SETOR B TERREO'),
('LAB. CNC','SALA','SETOR B TERREO'),
('SALA PREPARAÇÃO DOCENTES','SALA','SETOR B TERREO'),
('PROJETOS','SALA','SETOR B TERREO'),
('LAB. INFO 3','SALA','SETOR B TERREO'),
('COORDENAÇÃO SUPERIOR','SALA','SETOR B 1°. ANDAR'),
('SALA REUNIÃO SUPERIOR','SALA','SETOR B 1°. ANDAR'),
('LAB. AUTOMAÇÃO PREDIAL','SALA','SETOR B 1°. ANDAR'),
('SALA 1','SALA','SETOR B 1°. ANDAR'),
('SALA 2-AUDITÓRIO','SALA','SETOR B 1º. ANDAR'),
('SALA 3-AUDITÓRIO','SALA','SETOR B 1°. ANDAR'),
('SALA 4','SALA','SETOR B 1º. ANDAR'),
('SALA 5','SALA','SETOR B 1°. ANDAR'),
('LAB. INFO 4','SALA','SETOR B 1°. ANDAR'),
('RESIDUOS/TAMBORES SUCATA','SALA','EXTERNO'),
('COMPRESSORES','SALA','EXTERNO'),
('INVERSORES','SALA','EXTERNO'),
('DEPÓSITO ESCADA','SALA','EXTERNO'),
('DEPÓSITO DE ÓLEO','SALA','EXTERNO'),
('MDI','SALA','SUBSOLO'),
('SALA ESTAGIÁRIOS','SALA','SUBSOLO'),
('ALMOXARIFADO','SALA','SUBSOLO'),
('MANUTENÇÃO','SALA','SUBSOLO'),
('ZELADORIA','SALA','SUBSOLO'),
('DEPÓSTIO FUNDOS (FLUÍDOS)','SALA','EXTERNO'),
('SALA APOIΟ','SALA','SETOR A TERREO'),
('SALA DE REUNIÃO 1-NÚCLEO','SALA','SUBSOLO'),
('SALA DE REUNIÃO 1 - NÚCLEO','SALA','SUBSOLO');